import type { DefenderPoseState, ShooterPoseState } from "@/store/useShotStore";

export type PosePreset = {
  category: "pro" | "custom";
  defenderPose?: Partial<DefenderPoseState>;
  description: string;
  id: string;
  name: string;
  shooterPose: Partial<ShooterPoseState>;
};

export type DefenderPosePreset = {
  description: string;
  id: string;
  name: string;
  pose: Partial<DefenderPoseState>;
};

export const PROFESSIONAL_POSE_PRESETS: PosePreset[] = [
  {
    category: "pro",
    description: "Neutral base, vertical lift, compact release.",
    id: "balanced-jumper",
    name: "Balanced Jumper",
    shooterPose: {
      guideHandAngle: 28,
      handHeight: 9,
      isAirborne: true,
      jumpHeight: 7,
      kneeBend: 18,
      leftLegAngle: 8,
      releaseAngle: 50,
      rightLegAngle: -8,
      shootingArmAngle: 72,
      torsoAngle: 1,
      verticalOffset: 0.95,
    },
  },
  {
    category: "pro",
    description: "Fast pocket-to-release motion with low dip.",
    id: "catch-and-shoot",
    name: "Catch and Shoot",
    shooterPose: {
      guideHandAngle: 24,
      handHeight: 8.8,
      isAirborne: true,
      jumpHeight: 5.4,
      kneeBend: 13,
      leftLegAngle: 4,
      releaseAngle: 48,
      rightLegAngle: -4,
      shootingArmAngle: 82,
      torsoAngle: 4,
      verticalOffset: 0.62,
    },
  },
  {
    category: "pro",
    description: "One-dribble rhythm with a stronger gather.",
    id: "pull-up-jumper",
    name: "Pull-Up Jumper",
    shooterPose: {
      guideHandAngle: 30,
      handHeight: 9.2,
      isAirborne: true,
      jumpHeight: 7.8,
      kneeBend: 22,
      leftLegAngle: 14,
      releaseAngle: 50,
      rightLegAngle: -2,
      shootingArmAngle: 76,
      torsoAngle: 5,
      verticalOffset: 1.05,
    },
  },
  {
    category: "pro",
    description: "Backward torso lean with high release separation.",
    id: "fadeaway",
    name: "Fadeaway",
    shooterPose: {
      guideHandAngle: 32,
      handHeight: 9.5,
      isAirborne: true,
      jumpHeight: 8.4,
      kneeBend: 12,
      leftLegAngle: 18,
      releaseAngle: 55,
      rightLegAngle: 5,
      shootingArmAngle: 80,
      torsoAngle: -15,
      verticalOffset: 1.1,
    },
  },
  {
    category: "pro",
    description: "Space-creating base with slight backward drift.",
    id: "step-back",
    name: "Step Back",
    shooterPose: {
      guideHandAngle: 31,
      handHeight: 9.1,
      isAirborne: true,
      jumpHeight: 6.9,
      kneeBend: 20,
      leftLegAngle: -12,
      releaseAngle: 51,
      rightLegAngle: 12,
      shootingArmAngle: 78,
      torsoAngle: -8,
      verticalOffset: 0.88,
    },
  },
  {
    category: "pro",
    description: "Soft one-hand touch shot with earlier release.",
    id: "floater",
    name: "Floater",
    shooterPose: {
      guideHandAngle: 18,
      handHeight: 9.6,
      isAirborne: true,
      jumpHeight: 5.2,
      kneeBend: 10,
      leftLegAngle: 20,
      releaseAngle: 62,
      rightLegAngle: 8,
      shootingArmAngle: 86,
      torsoAngle: 7,
      verticalOffset: 0.7,
    },
  },
  {
    category: "pro",
    description: "Extended finish with body moving toward the rim.",
    id: "layup",
    name: "Layup",
    shooterPose: {
      guideHandAngle: 16,
      handHeight: 10.6,
      isAirborne: true,
      jumpHeight: 8.8,
      kneeBend: 8,
      leftLegAngle: 28,
      releaseAngle: 58,
      rightLegAngle: 20,
      shootingArmAngle: 88,
      torsoAngle: 10,
      verticalOffset: 1.35,
    },
  },
  {
    category: "pro",
    description: "Maximum vertical lift and direct rim finish.",
    id: "dunk",
    name: "Dunk",
    shooterPose: {
      guideHandAngle: 8,
      handHeight: 12,
      isAirborne: true,
      jumpHeight: 12,
      kneeBend: 5,
      leftLegAngle: 24,
      releaseAngle: 70,
      rightLegAngle: 18,
      shootingArmAngle: 95,
      torsoAngle: 6,
      verticalOffset: 1.8,
    },
  },
  {
    category: "pro",
    description: "Side-body shield with a high arcing release.",
    id: "hook-shot",
    name: "Hook Shot",
    shooterPose: {
      guideHandAngle: 12,
      handHeight: 10.4,
      isAirborne: true,
      jumpHeight: 4.8,
      kneeBend: 16,
      leftLegAngle: 15,
      releaseAngle: 64,
      rightLegAngle: -8,
      shootingArmAngle: 92,
      torsoAngle: 18,
      verticalOffset: 0.6,
    },
  },
  {
    category: "pro",
    description: "High-pressure defender with early vertical contest.",
    defenderPose: {
      armRaise: 98,
      contestHeight: 11,
      isAirborne: true,
      jumpHeight: 8.4,
      kneeBend: 7,
      leanAngle: -6,
      stanceWidth: 3.5,
      torsoAngle: -5,
      verticalOffset: 1.18,
    },
    id: "strong-contest",
    name: "Strong Contest",
    shooterPose: {
      guideHandAngle: 34,
      handHeight: 9.4,
      isAirborne: true,
      jumpHeight: 7.6,
      kneeBend: 13,
      releaseAngle: 53,
      shootingArmAngle: 84,
      torsoAngle: -6,
      verticalOffset: 1,
    },
  },
  {
    category: "pro",
    description: "Late hand pressure with a clean shooter window.",
    defenderPose: {
      armRaise: 48,
      contestHeight: 7.6,
      isAirborne: false,
      jumpHeight: 0,
      kneeBend: 20,
      leanAngle: 8,
      stanceWidth: 2.2,
      torsoAngle: 7,
      verticalOffset: 0,
    },
    id: "weak-contest",
    name: "Weak Contest",
    shooterPose: {
      guideHandAngle: 28,
      handHeight: 9.1,
      isAirborne: true,
      jumpHeight: 6.6,
      kneeBend: 16,
      releaseAngle: 50,
      shootingArmAngle: 76,
      torsoAngle: 0,
      verticalOffset: 0.9,
    },
  },
];

export const DEFENDER_POSE_PRESETS: DefenderPosePreset[] = [
  {
    description: "Chest square, low center of gravity, close pressure stance.",
    id: "close-defense",
    name: "Close Defense",
    pose: {
      armRaise: 72,
      contestHeight: 9.2,
      isAirborne: false,
      jumpHeight: 0,
      kneeBend: 30,
      leanAngle: -5,
      stanceWidth: 3.6,
      torsoAngle: -4,
      verticalOffset: 0,
    },
  },
  {
    description: "Wide feet and bent knees for containing a drive.",
    id: "low-stance",
    name: "Low Stance",
    pose: {
      armRaise: 48,
      contestHeight: 7.8,
      isAirborne: false,
      jumpHeight: 0,
      kneeBend: 42,
      leanAngle: 0,
      stanceWidth: 4.5,
      torsoAngle: 5,
      verticalOffset: 0,
    },
  },
  {
    description: "Both hands active with upright posture to bother vision.",
    id: "hands-up",
    name: "Hands Up",
    pose: {
      armRaise: 92,
      contestHeight: 10.4,
      isAirborne: false,
      jumpHeight: 0,
      kneeBend: 18,
      leanAngle: 0,
      stanceWidth: 2.8,
      torsoAngle: -2,
      verticalOffset: 0,
    },
  },
  {
    description: "Straight-up jump contest with high release obstruction.",
    id: "vertical-contest",
    name: "Vertical Contest",
    pose: {
      armRaise: 100,
      contestHeight: 11.2,
      isAirborne: true,
      jumpHeight: 8.4,
      kneeBend: 7,
      leanAngle: 0,
      stanceWidth: 2.7,
      torsoAngle: 0,
      verticalOffset: 1.2,
    },
  },
  {
    description: "Recovering from behind with forward lean and late hand.",
    id: "late-recovery",
    name: "Late Recovery",
    pose: {
      armRaise: 68,
      contestHeight: 8.4,
      isAirborne: false,
      jumpHeight: 0,
      kneeBend: 22,
      leanAngle: 16,
      stanceWidth: 2.2,
      torsoAngle: 12,
      verticalOffset: 0,
    },
  },
  {
    description: "Balanced no-foul posture with controlled hand pressure.",
    id: "verticality",
    name: "Verticality",
    pose: {
      armRaise: 86,
      contestHeight: 10,
      isAirborne: false,
      jumpHeight: 0,
      kneeBend: 20,
      leanAngle: 0,
      stanceWidth: 3,
      torsoAngle: 0,
      verticalOffset: 0,
    },
  },
];

export function createCustomPosePreset({
  defenderPose,
  name,
  shooterPose,
}: {
  defenderPose?: DefenderPoseState;
  name: string;
  shooterPose: ShooterPoseState;
}): PosePreset {
  // Custom presets snapshot all current joints so reloading them restores the
  // exact stickman posture the user saved from the simulator.
  return {
    category: "custom",
    defenderPose: defenderPose ? { ...defenderPose } : undefined,
    description: "Saved from the current simulator pose.",
    id: `custom-${Date.now()}`,
    name,
    shooterPose: { ...shooterPose },
  };
}
